//Users
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Rooms
export const SET_ROOMS = "SET_ROOMS";
export const FETCH_ROOMS_PENDING = "FETCH_ROOMS_PENDING";
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_ERROR = "FETCH_ROOMS_ERROR";
export const CREATE_ROOMS_ERROR = "CREATE_ROOMS_ERROR";
export const CREATE_ROOMS_SUCCESS = "CREATE_ROOMS_SUCCESS";

//Movies
export const FETCH_MOVIES_PENDING = "FETCH_MOVIES_PENDING";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";
export const CREATE_MOVIES_SUCCESS = "CREATE_MOVIES_SUCCESS";
export const CREATE_MOVIES_ERROR = "CREATE_MOVIES_ERROR";

//Seanses
export const FETCH_SEANSES_PENDING = "FETCH_SEANSES_PENDING";
export const FETCH_SEANSES_SUCCESS = "FETCH_SEANSES_SUCCESS";
export const FETCH_SEANSES_ERROR = "FETCH_SEANSES_ERROR";

export const CREATE_SEANSES_SUCCESS = "CREATE_SEANSES_SUCCESS";
export const CREATE_SEANSES_ERROR = "CREATE_SEANSES_ERROR";

export const UPDATE_SEANSES_SUCCESS = "UPDATE_SEANSES_SUCCESS";

export const FETCH_MOVIE_SEANCES_SUCCESS = "FETCH_MOVIE_SEANCES_SUCCESS";
export const FETCH_MOVIE_SEANCES_PENDING = "FETCH_MOVIE_SEANCES_PENDING";
export const FETCH_MOVIE_SEANCES_ERROR = "FETCH_MOVIE_SEANCES_ERROR";
